.Dd 2/6/13
.Dt olm_close_file 3 
.Os
.Sh NAME
.Nm olm_close_file
.Nd close an OLM file
.Sh LIBRARY
Outlook for Mac message extraction library (libolmec).
.Sh SYNOPSIS
.In libolmec.h
.Ft void
.Fn olm_close_file "olm_file_t *file" 
.Sh DESCRIPTION
The
.Fn olm_close_file
function will close an OLM file, previously opened using the
.Fn olm_open_file
function, and represented by the
.Fa file 
pointer. All memory and resources will be freed.

The
function will return immediately if
.Fa file
is NULL.

.Bf -symbolic
Passing anything other that a valid
.Ft olm_file_t
pointer to this function will have unpredictable results and very likely crash the library or your application.
.Ef
.Sh RETURN VALUES
None
.Sh ERRORS
None
.Sh SEE ALSO 
.Xr olm_open_file 3
.Sh BUGS
None
.Sh AUTHORS
Chris Morrison